version: "3.9"
services:
  bluegrass-app:
    networks:
      - bluegrass-quickstart
    container_name: bluegrass-app
    build: ../../Bluegrass/
    ports:
      - "8000:80"
    image: docker-compose_bluegrass-app
    depends_on:
      - bluegrass-sql
    volumes:
      - ./appsettings/appsettings.docker.json:/app/bluegrass/appsettings.json
  bluegrass-sql:
    networks:
        - bluegrass-quickstart
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: bluegrass-sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "12345OHdf%e"
      ACCEPT_EULA: "Y"

networks:
  bluegrass-quickstart: